### PR TITLE
ci: Locate file:line in golangci-lint

### LINKED ISSUE #18: Lint check failed
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
```
  Running [/home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  Error: File is not `goimports`-ed (goimports)
  
  Error: issues found
  Ran golangci-lint in 34803ms
```

### Describe what you expected to happen
Fix it.

### PR DESCRIPTION
**Pull request by jnan806**
Signed-off-by: Jiangnan Jia <jnan0806@gmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:

Now, the golangci-lint can not locate the file:line when lint occurs error,like following:
image

**Which issue(s) this PR fixes**:

Fixes #18 

**Describe how you did it**:
add args according https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648

### CODE REVIEW

**Comment by wilsonwu** [comment]
lgtm, @garroshh please help to review.

**Comment by garroshh** [comment]
LGTM

**Comment by wilsonwu** [comment]
@sczyh30 please help to merge, thanks.

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks!
@wilsonwu @garroshh Could you please submit another PR to fix "goimports" format error?

**Comment by wilsonwu** [comment]
@sczyh30 Yes, we are doing some enhancement for the operator, but currently this repo can't release docker image, so we can't use it directly, when the docker hub account ready, please let me know, we can move here for all.

**Comment by wilsonwu** [comment]
@sczyh30 Yes, we are doing some enhancement for the operator, but currently this repo can't release docker image, so we can't use it directly, when the docker hub account ready, please let me know, we can move here for all.

**Pull request merged**
